name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        default: 'all'
        type: choice
        options:
          - dev-02
          - dev-03
          - dev-04
          - dev-05
          - qa-01
          - qa-02
          - all
  pull_request:
    branches: ['development']
  push:
    branches: ['development', 'main']
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    outputs:
      docker-image-id: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: frandotidockeruser/testing
          username: franciscodotitexeira@gmail.com
          password: Yosoyyo123!

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
             frandotidockeruser/testing
          tags: |
            type=ref,enable=${{github.event_name == 'push'}},event=tag,prefix=hola

      
